### ISSUE TITLE
Configure Database and Localhost in application.properties

### ISSUE THREAD

**Issue by Ajayofficial18** [Ajayofficial18/fabrica-backend#1]
When setting up this Spring Boot project, the database and localhost settings need to be configured properly in the application.properties file to ensure the application works as expected.

Steps to Configure:

Database Configuration:
Replace the existing database URL, username, and password with your own values.
Example configuration:
properties

spring.datasource.url=jdbc:mysql://localhost:3306/your_database_name
spring.datasource.username=your_database_username
spring.datasource.password=your_database_password

Localhost Configuration:

Ensure that your application runs on the correct port and configure the server properties accordingly.
Example:
properties

server.port=8080

**Comment by thisisbatra** [comment]
Hi, ajay i'm new to open source as well as to hackertoberfest but i have a prior knowledge of springboot and want you to assign this issue to me.

**Comment by Ajayofficial18** [comment]
> Hi, ajay i'm new to open source as well as to hackertoberfest but i have a prior knowledge of springboot and want you to assign this issue to me.

No worries i will help you out, but you need to raise a pull request in an order to solve the issue.
